SELECT CASE WHEN count(*) = 0 THEN 'PASS:NO_CONTEXT_READ' ELSE 'FAIL:NO_CONTEXT_READ' END
FROM poc_customers;

BEGIN;
SET LOCAL app.tenant_id = 'TENANT-A';
SELECT CASE WHEN count(*) = 1 AND min(tenant_id) = 'TENANT-A'
  THEN 'PASS:TENANT_A_ONLY' ELSE 'FAIL:TENANT_A_ONLY' END
FROM poc_customers;
SELECT CASE WHEN count(*) = 0 THEN 'PASS:A_CANNOT_READ_B' ELSE 'FAIL:A_CANNOT_READ_B' END
FROM poc_customers
WHERE id = '22222222-2222-2222-2222-222222222222';
WITH changed AS (
  UPDATE poc_customers SET name = 'ILLEGAL-UPDATE'
  WHERE id = '22222222-2222-2222-2222-222222222222' RETURNING 1)
SELECT CASE WHEN count(*) = 0 THEN 'PASS:A_CANNOT_UPDATE_B' ELSE 'FAIL:A_CANNOT_UPDATE_B' END FROM changed;
WITH removed AS (
  DELETE FROM poc_customers
  WHERE id = '22222222-2222-2222-2222-222222222222' RETURNING 1)
SELECT CASE WHEN count(*) = 0 THEN 'PASS:A_CANNOT_DELETE_B' ELSE 'FAIL:A_CANNOT_DELETE_B' END FROM removed;
COMMIT;SELECT CASE WHEN count(*) = 0 THEN 'PASS:LOCAL_CONTEXT_CLEARED' ELSE 'FAIL:LOCAL_CONTEXT_CLEARED' END
FROM poc_customers;

BEGIN;
SET LOCAL app.tenant_id = 'TENANT-B';
SELECT CASE WHEN count(*) = 1 AND min(tenant_id) = 'TENANT-B'
  THEN 'PASS:TENANT_B_ONLY' ELSE 'FAIL:TENANT_B_ONLY' END
FROM poc_customers;
COMMIT;